version: '2'
services:
  proxy:
    image: traefik
    command: --docker --docker.domain=docker.localhost --logLevel=DEBUG --defaultentrypoints="Name:http Address::80"
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  ui:
    ports:
      - "3000"
    build:
      context: ./ui
      dockerfile: Dockerfile
    volumes:
      - ./ui:/app
    command: yarn start
    labels:
      - "traefik.backend=ui"
      - "traefik.frontend.rule=PathPrefix:/"
      - "traefik.port=3000"
      - "traefik.enable=true"
  api:
    environment:
      - ARANGODB_PASSWORD
      - ARANGODB_USERNAME
      - SPOTHIRE_SHARED_SECRET
    ports:
      - "3001"
    links:
      - arangodb
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api:/app
    command: yarn start
    labels:
      - "traefik.backend=api"
      - "traefik.frontend.rule=PathPrefix:/graphql"
      - "traefik.port=3001"
      - "traefik.enable=true"
  arangodb:
    environment:
      - ARANGO_ROOT_PASSWORD
    image: arangodb/arangodb:3.2.4
    volumes:
      - data:/var/lib/arangodb3
    ports:
      - "8529"
    labels:
      - "traefik.backend=arangodb"
      - "traefik.port=8529"
      - "traefik.enable=true"
volumes:
  data:
    driver: local
